### ISSUE TITLE
Hi, this plugin has the same issue as rhysd/accelerated-jk when using macro.

### ISSUE THREAD

**Issue by cstsunfu** [PHSix/faster.nvim#1]
The origin issue link is https://github.com/rhysd/accelerated-jk/issues/6.

**Comment by PHSix** [comment]
Thanks for you pointing out this bug, and I was fix it in newest commit.

**Comment by cstsunfu** [comment]
> Thanks for you pointing out this bug, and I was fix it in newest commit.

Cool, everything is working right now.
