### ISSUE TITLE
[Feature Request] Add support for gj and gk

### ISSUE THREAD

**Issue by Adnios** [PHSix/faster.nvim#2]
j and k are often mapped to gj and gk in `set wrap`.

It would be great to support for gj and gk. Like:
```
vim.api.nvim_set_keymap('n', 'j', '<Plug>(faster_move_gj)', {noremap=false, silent=true})
vim.api.nvim_set_keymap('n', 'k', '<Plug>(faster_move_gk)', {noremap=false, silent=true})
```

**Comment by PHSix** [comment]
Sorry, maybe I don't understand what you want to express. Could you describe more clearly again(maybe add a img or gif can make me more clear what you mean).

**Comment by PHSix** [comment]
> j and k are often mapped to gj and gk in `set wrap`.
> 
> It would be great to support for gj and gk. Like:
> 
> ```
> vim.api.nvim_set_keymap('n', 'j', '<Plug>(faster_move_gj)', {noremap=false, silent=true})
> vim.api.nvim_set_keymap('n', 'k', '<Plug>(faster_move_gk)', {noremap=false, silent=true})
> ```

Sorry, maybe I don't understand what you want to express. Could you describe more clearly again(maybe add a img or gif can make me more clear what you mean).
